version: "3"
services:
  gogs:
    image: docker.io/gogs/gogs:latest
    ports:
      - "10022:22"
      - "3000:3000"
    volumes:
      - $PWD/gogs:/data
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - gogs-net
networks: # 创建网络
  gogs-net:
